### PR TITLE
fix: Enum constructor clause

### LINKED ISSUE #10: Error when reaches a constructor on an enum
When the parser reaches a constructor on an enum, an error is thrown.

---
The following enum, for example, is enough to stop the parser from parsing.

```dart
enum ButtonState {
  up,
  upAndSelected,
  down,
  downAndSelected,
  hover,
  hoverAndSelected,
  disabled,
  disabledAndSelected;

  const ButtonState();

}
```

```
type 'EnumDeclarationImpl' is not a subtype of type 'ClassDeclaration' in type cast
#0      serializeConstructorDeclaration (package:dartdoc_json/src/constructor_declaration.dart:16:42)
#1      serializeMemberList (package:dartdoc_json/src/member_list.dart:18:14)
#2      serializeEnumDeclaration (package:dartdoc_json/src/enum_declaration.dart:30:16)
#3      serializeCompilationUnit (package:dartdoc_json/src/compilation_unit.dart:25:20)
```

The code assumes that the parent of the constructor is a class, but it is not the case. Recently, in dart, it was added more features to enums.

#### Additional resources:

 * <https://github.com/flame-engine/flame/blob/main/packages/flame/lib/src/components/input/advanced_button_component.dart>

### PR DESCRIPTION
**Pull request by bdlukaa**
Fixes #10

### CODE REVIEW

**Review by renancaraujo — APPROVED** [review]

**Review by spydon — APPROVED** [review]
Sorry I completely missed this PR! Feel free to ping me if it happens again 😅
Can you fix the small formatting issue so that the pipeline becomes green?

**Comment by renancaraujo** [comment]
I think even `main` build CI is red. LGTM.

**Comment by spydon** [comment]
> I think even `main` build CI is red. LGTM.

Fixed!

**Comment by spydon** [comment]
@bdlukaa your changes are now released in 0.3.0, sorry for the delay!

**Pull request merged**
